version: '3.8'

services:
  app:
    build:
      context: ./docker/server/
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:80" #ホストの8000ポートをコンテナの80ポートにマッピング
    volumes:
      - ./SampleProject:/var/www/html/SampleProject
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: riku1230syun5513
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306" #ホストの3306ポートをコンテナの3306ポートにマッピング
    volumes:
      - db-data:/var/lib/mysql
  
volumes:
  db-data:
